### ISSUE TITLE
Trouble loading scala library

### ISSUE THREAD

**Issue by bbarker** [skaldarnar/ScalaLib#4]
I'm not sure if this is a result of the scala library being a nested jar within the module jar. Are there any other examples of how to handle external dependencies in modules?:

```
21:02:15.176 [main] ERROR o.t.p.serializers.PrefabSerializer - Prefab contains unknown component 'ChangingBlocks'
21:02:16.613 [main] ERROR o.t.e.event.internal.EventSystemImpl - Invalid event handler method: componentUpdated
21:02:16.613 [main] ERROR o.t.e.event.internal.EventSystemImpl - Invalid event handler method: componentUpdated
21:02:17.333 [main] ERROR o.t.engine.ComponentSystemManager - Failed to load system ScalaLib:ScalaCommands
java.lang.NoClassDefFoundError: scala/collection/Seq
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at org.terasology.engine.ComponentSystemManager.loadSystems(ComponentSystemManager.java:96)
        at org.terasology.engine.modes.loadProcesses.RegisterSystems.step(RegisterSystems.java:53)
        at org.terasology.engine.modes.StateLoading.update(StateLoading.java:242)
        at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:437)
        at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:400)
        at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:376)
        at org.terasology.engine.Terasology.main(Terasology.java:154)
Caused by: java.lang.ClassNotFoundException: Failed to find or load class scala.collection.Seq
        at org.terasology.module.sandbox.ModuleClassLoader.findClass(ModuleClassLoader.java:158)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.terasology.module.sandbox.ModuleClassLoader.loadClass(ModuleClassLoader.java:121)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 11 common frames omitted
Caused by: javassist.NotFoundException: scala.collection.Seq
        at javassist.ClassPool.get(ClassPool.java:452)
        at org.terasology.module.sandbox.ModuleClassLoader$1.run(ModuleClassLoader.java:145)
        at org.terasology.module.sandbox.ModuleClassLoader$1.run(ModuleClassLoader.java:142)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.terasology.module.sandbox.ModuleClassLoader.findClass(ModuleClassLoader.java:142)
        ... 14 common frames omitted
21:02:17.335 [main] WARN  o.t.engine.internal.TimeBase - Delta too great (2174), capping to 1000
```

I also tried adding the following to the `PACKAGES` whitelist in`engine/src/main/java/org/terasology/engine/module/ExternalApiWhitelist.java` but this didn't seem to help: 

```java
            .add("scala.lang")
            .add("scala.collection")
```

**Comment by skaldarnar** [comment]
There is also [KotlinLib](https://github.com/Terasology/KotlinLib), but I think it works in a similar fashion. The special handling for external libs is (partly) attributed to our build setup that does not allow for external dependencies, and in order to make the external dependency available to other modules.

I'll have to look into this in detail, been some time now since I last checked this module…

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
